name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Go Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: sample-cache
          key: ${{ runner.os }}-sample-cache-${{ hashFiles('**/package.json') }}
        
      - name: inject sample-cache into docker
        uses: overmindtech/buildkit-cache-dance/inject@main
        with:
          cache-source: sample-cache

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: build/package/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.sha }}
          labels: main
          platforms: linux/amd64

      - name: extract sample-cache from docker
        uses: overmindtech/buildkit-cache-dance/extract@main
        with:
          cache-source: sample-cache

